version: '3.9'

services:

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_DB=pismo_local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ra5hoxetRami5
      - POSTGRES_PORT=5432
    volumes:
      - postgresvolume:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"

  pismo_service:
    container_name: pismo_service
    build: 
      context: .
      dockerfile: ./build/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - HOST_TYPE=local
      - DATABASE_POSTGRES_SOURCE_DB_NAME=pismo_local
      - DATABASE_POSTGRES_SOURCE_USER=postgres
      - DATABASE_POSTGRES_SOURCE_PASSWORD=ra5hoxetRami5
      - DATABASE_POSTGRES_SOURCE_PORT=5432
      - DATABASE_POSTGRES_SOURCE_HOST=postgres
    depends_on:
      - postgres
      - redis

volumes:
  postgresvolume:


 