// Code generated by mockery v2.42.1. DO NOT EDIT.

package repository_mocks

import mock "github.com/stretchr/testify/mock"

// ITransactionRepo is an autogenerated mock type for the ITransactionRepo type
type ITransactionRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: model, tableMame
func (_m *ITransactionRepo) Create(model interface{}, tableMame string) error {
	ret := _m.Called(model, tableMame)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, string) error); ok {
		r0 = rf(model, tableMame)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewITransactionRepo creates a new instance of ITransactionRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITransactionRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITransactionRepo {
	mock := &ITransactionRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
