database:
  postgres:
    source:
      host: $POSTGRES_HOST
      port: $POSTGRES_PORT
      user: $POSTGRES_USER
      password: $POSTGRES_PASSWORD
      db_name: $POSTGRES_DB

logging:
  format: "json"
  level: "info"