// Code generated by mockery v2.42.1. DO NOT EDIT.

package service_mocks

import (
	dto "self-projects/pismo/internal/app/pismo/dto"

	mock "github.com/stretchr/testify/mock"

	request_context "self-projects/pismo/pkg/request_context"
)

// IOperationTypeService is an autogenerated mock type for the IOperationTypeService type
type IOperationTypeService struct {
	mock.Mock
}

// CreateOperationType provides a mock function with given fields: rCtx, reqBody
func (_m *IOperationTypeService) CreateOperationType(rCtx *request_context.ReqCtx, reqBody *dto.OperationTypeCreateRequest) (*dto.OperationTypeCreateResponse, error) {
	ret := _m.Called(rCtx, reqBody)

	if len(ret) == 0 {
		panic("no return value specified for CreateOperationType")
	}

	var r0 *dto.OperationTypeCreateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*request_context.ReqCtx, *dto.OperationTypeCreateRequest) (*dto.OperationTypeCreateResponse, error)); ok {
		return rf(rCtx, reqBody)
	}
	if rf, ok := ret.Get(0).(func(*request_context.ReqCtx, *dto.OperationTypeCreateRequest) *dto.OperationTypeCreateResponse); ok {
		r0 = rf(rCtx, reqBody)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.OperationTypeCreateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*request_context.ReqCtx, *dto.OperationTypeCreateRequest) error); ok {
		r1 = rf(rCtx, reqBody)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIOperationTypeService creates a new instance of IOperationTypeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIOperationTypeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IOperationTypeService {
	mock := &IOperationTypeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
